<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Layers\Author\AuthorService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Config\" />
    <Folder Include="Types\DTOs\" />
    <Folder Include="Types\Interfaces\" />
    <Folder Include="Middleware\" />
    <Folder Include="Data\Exceptions\" />
    <Folder Include="Data\Enums\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Layers\Author\AuthorService.cs" />
  </ItemGroup>

</Project>
